server:
  tomcat: 
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
spring:
  application:
    name: foundation
  jpa:
        open-in-view: true
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
  database:
      driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
      platform: mysql
      url: jdbc:mysql://foundation_mysql:3306/demo?characterEncoding=utf8
      username: root
      password: 654321
      test-while-idle: true
      validation-query: SELECT 1
  
      
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
    '[com.donationsystem]': DEBUG
  file:
    name: ./logs/foundation.log

encrypt-type: # 0:standard, 1:guomi
  encrypt-type: 0

group-channel-connections-config:
  caCert: ca.crt
  sslCert: sdk.crt
  sslKey: sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 172.100.0.2:20200 
        - 172.100.0.3:20200
        - 172.100.0.4:20200
        - 172.100.0.5:20200

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: foundation # agency name



accounts:
  pem-file: 0x1356943c6b6cfd3ff42aec3a6cb863135108e804.pem
  p12-file: 0xc213ad2f1ff1d1e93f0e84cd71ba7aa29b8ec819.p12
  password: 123456
