FROM openjdk:11
LABEL maintainer=shiki92
WORKDIR /app
COPY platform platform
COPY start.sh start.sh
RUN cd platform/backend && ./gradlew && ./gradlew build -x test
ENTRYPOINT [ "bash" ,"/app/start.sh"]