FROM openjdk:11
LABEL maintainer=shiki92
WORKDIR /app
COPY foundation foundation
COPY start.sh start.sh
RUN cd /tmp/ && curl -k -LO "https://files.cnblogs.com/files/zgngg/jce_policy-8.zip" && unzip jce_policy-8.zip && rm jce_policy-8.zip && cp -v /tmp/UnlimitedJCEPolicyJDK8/*.jar /usr/local/openjdk-11/lib/security && cd /app/foundation && ./gradlew
ENTRYPOINT [ "bash" ,"/app/start.sh"]