version: '3'
services: 
  foundationNode:
    image: shiki92/foundation_node:latest
    volumes: 
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/foundation/console/accounts:/fisco/console/accounts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/foundation/console/contracts:/fisco/console/contracts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/foundation/node:/fisco/node/node"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/shell/foundation:/fisco/shell"
    ports: 
      - "20201:20200"
    networks: 
      fisco_net:
        ipv4_address: 172.100.0.2
    deploy:
      resources:
        limits:
          memory: 250M

  logisticNode:
    image: shiki92/logistic_node:latest
    volumes: 
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/logistic/console/accounts:/fisco/console/accounts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/logistic/console/contracts:/fisco/console/contracts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/logistic/node:/fisco/node/node"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/shell/logistic:/fisco/shell"
    ports: 
      - "20202:20200"
    networks: 
      fisco_net:
        ipv4_address: 172.100.0.3
    deploy:
      resources:
        limits:
          memory: 250M

  hospitalNode:
    image: shiki92/hospital_node:latest
    volumes: 
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/hospital/console/accounts:/fisco/console/accounts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/hospital/console/contracts:/fisco/console/contracts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/hospital/node:/fisco/node/node"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/shell/hospital:/fisco/shell"
    ports: 
      - "20203:20200"
    networks: 
      fisco_net:
        ipv4_address: 172.100.0.4
    deploy:
      resources:
        limits:
          memory: 250M

  platformNode:
    image: shiki92/platform_node:latest
    volumes: 
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/platform/console/accounts:/fisco/console/accounts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/platform/console/contracts:/fisco/console/contracts"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/platform/node:/fisco/node/node"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/shell/platform:/fisco/shell"
    ports: 
      - "20204:20200"
    networks: 
      fisco_net:
        ipv4_address: 172.100.0.5
    deploy:
      resources:
        limits:
          memory: 250M

  # foundationApp:
  #   image: shiki92/ds_foundation:latest
  #   volumes: 
  #     - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/foundation/jar/db:/app/db"
  #     - "/home/gongyueyang/BlockChain/DonationSystem/docker/logs/foundation:/app/logs/"
  #   ports: 
  #     - "8081:8080"
  #   networks: 
  #     fisco_net:
  #       ipv4_address: 172.100.0.6
  #   depends_on: 
  #       - platformApp
  #       - logisticApp

  # logisticApp:
  #   image: shiki92/ds_logistic:latest
  #   volumes: 
  #     - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/logistic/jar/db:/app/db"
  #     - "/home/gongyueyang/BlockChain/DonationSystem/docker/logs/logistic:/app/logs/"
  #   ports: 
  #     - "8082:8080"
  #   networks: 
  #     fisco_net:
  #       ipv4_address: 172.100.0.7
  #   depends_on: 
  #       - platformApp

  # hospitalApp:
  #   image: shiki92/ds_hospital:latest
  #   volumes: 
  #     - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/hospital/jar/db:/app/db"
  #     - "/home/gongyueyang/BlockChain/DonationSystem/docker/logs/hospital:/app/logs/"
  #   ports: 
  #     - "8083:8080"
  #   networks: 
  #     fisco_net:
  #       ipv4_address: 172.100.0.8

  platformApp:
    image: shiki92/ds_platform:latest
    volumes: 
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/data/platform/jar/db:/app/db"
      - "/home/gongyueyang/BlockChain/DonationSystem/docker/logs/platform:/app/logs/"
    ports: 
      - "8084:8080"
    networks: 
      fisco_net:
        ipv4_address: 172.100.0.9
  
networks: 
  fisco_net:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.100.0.0/16
          gateway: 172.100.0.1
