encrypt-type: # 0:standard, 1:guomi
  encrypt-type: 0

group-channel-connections-config:
  caCert: ca.crt
  sslCert: sdk.crt
  sslKey: sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 172.18.0.3:20200 
        - 172.18.0.2:20200
        - 172.18.0.4:20200
        - 172.18.0.5:20200

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: logistic # agency name



accounts:
  pem-file: 0x1db86fe8945aac3bb27469a34e3906738fa7cc3a.pem
  p12-file: 0xd6f49ae4bdb0e340b74b70f43ba529e85254657e.p12
  password: 123456

# server:
#   tomcat:
#     uri-encoding: UTF-8
#     threads:
#       max: 1000
#       min-spare: 30
#   port: 8080
# spring:
#   datasource:
#     type: com.alibaba.druid.pool.DruidDataSource
#     url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     username: root
#     password: 654321

#   jpa:
#     database: mysql
#     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#     properties:
#       hibernate:
#         ddl:
#           auto: create-drop