server:
  tomcat: 
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
spring:
  groovy:
    template:
      check-template-location: false
  application:
    name: platform
  jpa:
    open-in-view: true
    database: h2
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect      
  datasource:
    platform: h2
    url: jdbc:h2:./db/h2
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
      
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
    '[com.donationsystem]': DEBUG
  file:
    name: ./logs/platform.log

encrypt-type: # 0:standard, 1:guomi
  encrypt-type: 0

group-channel-connections-config:
  caCert: ca.crt
  sslCert: sdk.crt
  sslKey: sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 172.100.0.2:20200 
        - 172.100.0.3:20200
        - 172.100.0.4:20200
        - 172.100.0.5:20200

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: platform # agency name



accounts:
  pem-file: 0x1356943c6b6cfd3ff42aec3a6cb863135108e804.pem
  p12-file: 
  password: 

# server:
#   tomcat: 
#     uri-encoding: UTF-8
#     threads:
#       max: 1000
#       min-spare: 30
#   port: 8084
# spring:
#   groovy:
#     template:
#       check-template-location: false
#   application:
#     name: platform
#   jpa:
#     open-in-view: true
#     database: h2
#     show-sql: true
#     hibernate:
#         ddl-auto: update
#     properties:
#         hibernate:
#             dialect: org.hibernate.dialect.H2Dialect      
#   datasource:
#     platform: h2
#     url: jdbc:h2:./db/h2
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: 

# encrypt-type: # 0:standard, 1:guomi
#   encrypt-type: 0

# group-channel-connections-config:
#   caCert: ca.crt
#   sslCert: sdk.crt
#   sslKey: sdk.key
#   all-channel-connections:
#     - group-id: 1 #group ID
#       connections-str:
#         - 127.0.0.1:20201
#         - 127.0.0.1:20202
#         - 127.0.0.1:20203
#         - 127.0.0.1:20204

# channel-service:
#   group-id: 1 # The specified group to which the SDK connects
#   agency-name: platform # agency name



# accounts:
#   pem-file: 0x1356943c6b6cfd3ff42aec3a6cb863135108e804.pem
#   p12-file: 
#   password: 
      

      
