server:
  tomcat: 
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8083
spring:
  application:
    name: hospital
  jpa:
        open-in-view: true
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
  database:
      driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
      platform: mysql
      # url: jdbc:mysql://hospital_mysql:3306/demo?characterEncoding=utf8
      url: jdbc:mysql://localhost:3309/demo?characterEncoding=utf8
      username: root
      password: 654321
      test-while-idle: true
      validation-query: SELECT 1
  
      
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
    '[com.donationsystem]': DEBUG
  file:
    name: ./logs/hospital.log

encrypt-type: # 0:standard, 1:guomi
  encrypt-type: 0

group-channel-connections-config:
  caCert: ca.crt
  sslCert: sdk.crt
  sslKey: sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        # - 172.100.0.2:20200 
        # - 172.100.0.3:20200
        # - 172.100.0.4:20200
        # - 172.100.0.5:20200
        - 127.0.0.1:20201
        - 127.0.0.1:20202
        - 127.0.0.1:20203
        - 127.0.0.1:20204

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: hospital # agency name



accounts:
  pem-file: 0xe4040677ef4147667afe9b2fa4818048dd044c0d.pem
  p12-file: 
  password: 

